name: 构建网站

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 设置 Node.js 和 pnpm
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: 安装 pnpm
        run: npm install -g pnpm

      - name: 安装依赖
        run: pnpm install --no-frozen-lockfile

      - name: 构建
        run: pnpm build

      - name: 部署到 Github Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          repo: NotFaceGUI/NotFaceGUI.github.io
          target_branch: gh-pages
          build_dir: ./dist
        env:
          GH_PAT: NotFaceGUI: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

