name: 构建网站

on:
  push:
    branches:
      - master

  workflow_dispatch:

permissions: write-all

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 设置 Node.js 和 pnpm
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: 安装 pnpm
        run: pnpm install --no-frozen-lockfile

      - name: 缓存依赖
        uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: 安装依赖
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: 构建
        run: pnpm run build

      - name: 部署到 Github Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gh-pages
          build_dir: ./dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
